### ISSUE TITLE
Deploying the ONOS shim

### ISSUE THREAD

**Issue by ElisaRojas** [fp7-netide/Engine#77]
Hi,

I compiled ONOS1.4 + the onos-shim project. Then add it with "onos-app" and activate it with "app activate" once in Karaf. No problem until this point. However, the combination with the Ryu backend and the Python core is not working and if I check log:display, I see the following:

```
2016-02-29 17:43:41,547 | INFO  | qtp720554492-50  | ApplicationManager               | 76 - org.onosproject.onos-core-net - 1.4.1.SNAPSHOT | Application eu.netide.shim has been installed
2016-02-29 17:46:05,527 | WARN  | l for user karaf | ApplicationManager               | 76 - org.onosproject.onos-core-net - 1.4.1.SNAPSHOT | Unable to perform operation on application eu.netide.shim
Could not start bundle mvn:eu.netide/onos-app-shim/1.0.0-SNAPSHOT in feature(s) onos-app-shim-1.0.0-SNAPSHOT: Unresolved constraint in bundle eu.netide.onos-app-shim [184]: Unable to resolve 184.0: missing requirement [184.0] osgi.wiring.package; (&(osgi.wiring.package=eu.netide.lib.netip)(version>=1.1.0)(!(version>=2.0.0)))
```

Is it somehow related to #67 ?
Could you help me on this @amarsico ? Thank you!

**Comment by amarsico** [comment]
Hi @ElisaRojas,
now the master works, the problem was in the NetIP version number.

**Comment by ElisaRojas** [comment]
Hi @amarsico ,

A colleague tried to recompile and check again the ONOS shim and he obtained this error now:

```
2016-03-04 12:39:02,703 | WARN  | l for user karaf | ApplicationManager               | 76 - org.onosproject.onos-core-net - 1.4.1.SNAPSHOT | Unable to perform operation on application eu.netide.shim
java.lang.IllegalStateException: Can't install feature onos-app-shim/0.0.0:     
Could not start bundle mvn:eu.netide/onos-app-shim/1.0.0-SNAPSHOT in feature(s) onos-app-shim-1.0.0-SNAPSHOT: Uses constraint violation. Unable to resolve bundle revision eu.netide.onos-app-shim [184.0] because it is exposed to package 'org.projectfloodlight.openflow.protocol' from bundle revisions netip [183.0] and org.onosproject.onos-of-api [161.0] via two dependency chains.

Chain 1:
  eu.netide.onos-app-shim [184.0]
    import: (&(osgi.wiring.package=org.projectfloodlight.openflow.protocol)(version>=1.1.0)(!(version>=2.0.0)))
     |
    export: osgi.wiring.package=org.projectfloodlight.openflow.protocol
  netip [183.0]

Chain 2:
  eu.netide.onos-app-shim [184.0]
    import: (&(osgi.wiring.package=org.onosproject.openflow.controller)(version>=1.4.0)(!(version>=2.0.0)))
     |
    export: osgi.wiring.package=org.onosproject.openflow.controller; uses:=org.projectfloodlight.openflow.protocol
    export: osgi.wiring.package=org.projectfloodlight.openflow.protocol
  org.onosproject.onos-of-api [161.0]
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:388)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:359)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:337)
    at Proxy4d9a2c46_764e_4cae_9b5a_9a990dceda49.installFeature(Unknown Source)
    at org.onosproject.app.impl.ApplicationManager.installAppFeatures(ApplicationManager.java:253)
    at org.onosproject.app.impl.ApplicationManager.access$100(ApplicationManager.java:56)
    at org.onosproject.app.impl.ApplicationManager$InternalStoreDelegate.notify(ApplicationManager.java:184)
    at org.onosproject.app.impl.ApplicationManager$InternalStoreDelegate.notify(ApplicationManager.java:177)
    at org.onosproject.store.app.GossipApplicationStore$InternalAppStatesListener.event(GossipApplicationStore.java:398)
    at org.onosproject.store.ecmap.EventuallyConsistentMapImpl.lambda$notifyListeners$9(EventuallyConsistentMapImpl.java:512)
    at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)[:1.8.0_72]
    at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404)[:1.8.0_72]
    at org.onosproject.store.ecmap.EventuallyConsistentMapImpl.notifyListeners(EventuallyConsistentMapImpl.java:512)
    at org.onosproject.store.ecmap.EventuallyConsistentMapImpl.put(EventuallyConsistentMapImpl.java:323)
    at org.onosproject.store.app.GossipApplicationStore.activate(GossipApplicationStore.java:316)
    at org.onosproject.store.app.GossipApplicationStore.activate(GossipApplicationStore.java:305)
    at org.onosproject.store.app.GossipApplicationStore.activate(GossipApplicationStore.java:300)
    at org.onosproject.app.impl.ApplicationManager.activate(ApplicationManager.java:161)
    at org.onosproject.cli.app.ApplicationCommand.manageApp(ApplicationCommand.java:93)
    at org.onosproject.cli.app.ApplicationCommand.execute(ApplicationCommand.java:60)
    at org.onosproject.cli.AbstractShellCommand.doExecute(AbstractShellCommand.java:129)
    at org.apache.karaf.shell.console.AbstractAction.execute(AbstractAction.java:33)[25:org.apache.karaf.shell.console:3.0.3]
    at org.apache.karaf.shell.commands.basic.AbstractCommand.execute(AbstractCommand.java:33)[25:org.apache.karaf.shell.console:3.0.3]
    at Proxy19497013_5f45_4b6f_9efb_0413dfbf0145.execute(Unknown Source)[:]
    at Proxy19497013_5f45_4b6f_9efb_0413dfbf0145.execute(Unknown Source)[:]
    at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:78)[25:org.apache.karaf.shell.console:3.0.3]
    at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)[25:org.apache.karaf.shell.console:3.0.3]
    at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)[25:org.apache.karaf.shell.console:3.0.3]
    at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)[25:org.apache.karaf.shell.console:3.0.3]
    at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)[25:org.apache.karaf.shell.console:3.0.3]
    at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)[25:org.apache.karaf.shell.console:3.0.3]
    at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:92)
    at org.apache.karaf.shell.console.impl.jline.ConsoleImpl.run(ConsoleImpl.java:208)
    at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1$1.run(LocalConsoleManager.java:109)
    at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_72]
    at org.apache.karaf.jaas.modules.JaasHelper.doAs(JaasHelper.java:57)[26:org.apache.karaf.jaas.modules:3.0.3]
    at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1.run(LocalConsoleManager.java:102)[25:org.apache.karaf.shell.console:3.0.3]
```

Any idea? No rush :)

**Comment by amarsico** [comment]
Hi @ElisaRojas, 
This happens because I think that @schwabe has changed the `<Export-Packages>` in the NetIP pom.xml. In order to make it work again, you should delete line 114 `org.projectfloodlight.openflow.*` from the NetIP pom.xml and then compile it again. This creates a wrong dependency chain for OSGi, because when using the NetIP with ONOS, the Openflow libraries are already "Exported" from the ONOS OpenFlow API.

The pull request #74 should resolve all the dependency problem for NetIP, CORE and ONOS shim. @schwabe said that he will check after the review.

Best

**Comment by ElisaRojas** [comment]
Thank you @amarsico , let's check this after the review, yes :)

**Comment by amarsico** [comment]
@schwabe Have you check the modifications to NetIP pom.xml that I proposed to @ElisaRojas?  We need to fix the export/import issues to make everything work.

**Comment by ElisaRojas** [comment]
Hi again,

Sorry for reopening this, but my colleague tried the new code with Ryu + Java core + ONOS + Mininet. And he gets this error after deploying everything but Mininet:

```
onos> 
onos> Exception in thread "ZeroMQBasedConnector Receive Loop" java.lang.NoClassDefFoundError: org/jboss/netty/buffer/ChannelBuffer
    at eu.netide.lib.netip.NetIPConverter.parseConcreteMessage(NetIPConverter.java:18)
    at eu.netide.shim.ZeroMQBaseConnector.run(ZeroMQBaseConnector.java:125)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.jboss.netty.buffer.ChannelBuffer not found by netip [183]
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1532)
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 3 more
```

And then, after running Mininet he gets:

```
2016-03-14 12:01:29,932 | ERROR | ew I/O worker #8 | OFChannelHandler                 | 170 - org.onosproject.onos-of-ctl - 1.4.1.SNAPSHOT | Error while processing message from switch org.onosproject.driver.handshaker.NiciraSwitchHandshaker [/127.0.0.1:60513 DPID[00:00:00:00:00:00:00:01]]state WAIT_DESCRIPTION_STAT_REPLY
java.lang.NoClassDefFoundError: org/jboss/netty/buffer/ChannelBuffer
    at eu.netide.shim.NetIDEShimController.sendOpenFlowMessageToCore(NetIDEShimController.java:175)
    at eu.netide.shim.NetIDEDeviceListener.switchAdded(NetIDEDeviceListener.java:72)
    at org.onosproject.openflow.controller.impl.OpenFlowControllerImpl$OpenFlowSwitchAgent.addConnectedSwitch(OpenFlowControllerImpl.java:497)
    at org.onosproject.openflow.controller.driver.AbstractOpenFlowSwitch.connectSwitch(AbstractOpenFlowSwitch.java:264)
    at org.onosproject.openflow.controller.impl.OFChannelHandler$ChannelState$6.processOFStatisticsReply(OFChannelHandler.java:457)
    at org.onosproject.openflow.controller.impl.OFChannelHandler$ChannelState.processOFMessage(OFChannelHandler.java:892)
    at org.onosproject.openflow.controller.impl.OFChannelHandler.messageReceived(OFChannelHandler.java:1166)
    at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36)[44:org.jboss.netty:3.9.2.Final]
    at org.jboss.netty.handler.timeout.ReadTimeoutHandler.messageReceived(ReadTimeoutHandler.java:184)[44:org.jboss.netty:3.9.2.Final]
    at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294)[44:org.jboss.netty:3.9.2.Final]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)[44:org.jboss.netty:3.9.2.Final]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)[44:org.jboss.netty:3.9.2.Final]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)[44:org.jboss.netty:3.9.2.Final]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)[44:org.jboss.netty:3.9.2.Final]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)[44:org.jboss.netty:3.9.2.Final]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)[44:org.jboss.netty:3.9.2.Final]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)[44:org.jboss.netty:3.9.2.Final]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)[44:org.jboss.netty:3.9.2.Final]
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)[44:org.jboss.netty:3.9.2.Final]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)[44:org.jboss.netty:3.9.2.Final]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_72]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_72]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_72]
Caused by: java.lang.ClassNotFoundException: org.jboss.netty.buffer.ChannelBuffer not found by netip [183]
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1532)
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_72]
    ... 24 more
```

Any idea of what could it be? Thank you!

**Comment by ralvarep** [comment]
Issue fixed in #78

**Comment by ralvarep** [comment]
Hi,

I am testing again the ONOS shim and I get a similar error like the one that @ElisaRojas wrote a few days ago. I add onos-app and when I activate the app in Karaf the log displays:

```
2016-03-29 15:30:11,738 | WARN  | l for user karaf | ApplicationManager               | 76 - org.onosproject.onos-core-net - 1.4.1.SNAPSHOT | Unable to perform operation on application eu.netide.shim
java.lang.IllegalStateException: Can't install feature onos-app-shim/0.0.0:     
Could not start bundle mvn:eu.netide/onos-app-shim/1.0.0-SNAPSHOT in feature(s) onos-app-shim-1.0.0-SNAPSHOT: Uses constraint violation. Unable to resolve bundle revision eu.netide.onos-app-shim [183.0] because it is exposed to package 'org.projectfloodlight.openflow.protocol' from bundle revisions netip [182.0] and org.onosproject.onos-of-api [161.0] via two dependency chains.

Chain 1:
  eu.netide.onos-app-shim [183.0]
    import: (&(osgi.wiring.package=org.projectfloodlight.openflow.protocol)(version>=1.1.0)(!(version>=2.0.0)))
     |
    export: osgi.wiring.package=org.projectfloodlight.openflow.protocol
  netip [182.0]

Chain 2:
  eu.netide.onos-app-shim [183.0]
    import: (&(osgi.wiring.package=org.onosproject.openflow.controller)(version>=1.4.0)(!(version>=2.0.0)))
     |
    export: osgi.wiring.package=org.onosproject.openflow.controller; uses:=org.projectfloodlight.openflow.protocol
    export: osgi.wiring.package=org.projectfloodlight.openflow.protocol
  org.onosproject.onos-of-api [161.0]
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:388)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:359)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:337)
    at Proxy38f68848_ccbe_4df4_b0a4_a362a23515f3.installFeature(Unknown Source)
    at org.onosproject.app.impl.ApplicationManager.installAppFeatures(ApplicationManager.java:253)
    at org.onosproject.app.impl.ApplicationManager.access$100(ApplicationManager.java:56)
    at org.onosproject.app.impl.ApplicationManager$InternalStoreDelegate.notify(ApplicationManager.java:184)
    at org.onosproject.app.impl.ApplicationManager$InternalStoreDelegate.notify(ApplicationManager.java:177)
    at org.onosproject.store.app.GossipApplicationStore$InternalAppStatesListener.event(GossipApplicationStore.java:398)
    at org.onosproject.store.ecmap.EventuallyConsistentMapImpl.lambda$notifyListeners$9(EventuallyConsistentMapImpl.java:512)
    at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)[:1.8.0_72]
    at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404)[:1.8.0_72]
    at org.onosproject.store.ecmap.EventuallyConsistentMapImpl.notifyListeners(EventuallyConsistentMapImpl.java:512)
    at org.onosproject.store.ecmap.EventuallyConsistentMapImpl.put(EventuallyConsistentMapImpl.java:323)
    at org.onosproject.store.app.GossipApplicationStore.activate(GossipApplicationStore.java:316)
    at org.onosproject.store.app.GossipApplicationStore.activate(GossipApplicationStore.java:305)
    at org.onosproject.store.app.GossipApplicationStore.activate(GossipApplicationStore.java:300)
    at org.onosproject.app.impl.ApplicationManager.activate(ApplicationManager.java:161)
    at org.onosproject.cli.app.ApplicationCommand.manageApp(ApplicationCommand.java:93)
    at org.onosproject.cli.app.ApplicationCommand.execute(ApplicationCommand.java:60)
    at org.onosproject.cli.AbstractShellCommand.doExecute(AbstractShellCommand.java:129)
    at org.apache.karaf.shell.console.AbstractAction.execute(AbstractAction.java:33)[25:org.apache.karaf.shell.console:3.0.3]
    at org.apache.karaf.shell.commands.basic.AbstractCommand.execute(AbstractCommand.java:33)[25:org.apache.karaf.shell.console:3.0.3]
    at Proxyf27a8f9f_46d0_47e5_b6b4_f1477dec716e.execute(Unknown Source)[:]
    at Proxyf27a8f9f_46d0_47e5_b6b4_f1477dec716e.execute(Unknown Source)[:]
    at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:78)[25:org.apache.karaf.shell.console:3.0.3]
    at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)[25:org.apache.karaf.shell.console:3.0.3]
    at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)[25:org.apache.karaf.shell.console:3.0.3]
    at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)[25:org.apache.karaf.shell.console:3.0.3]
    at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)[25:org.apache.karaf.shell.console:3.0.3]
    at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)[25:org.apache.karaf.shell.console:3.0.3]
    at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:92)
    at org.apache.karaf.shell.console.impl.jline.ConsoleImpl.run(ConsoleImpl.java:208)
    at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1$1.run(LocalConsoleManager.java:109)
    at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_72]
    at org.apache.karaf.jaas.modules.JaasHelper.doAs(JaasHelper.java:57)[26:org.apache.karaf.jaas.modules:3.0.3]
    at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1.run(LocalConsoleManager.java:102)[25:org.apache.karaf.shell.console:3.0.3]
```

@amarsico, could you help me?
Thanks in advance.

**Comment by amarsico** [comment]
@ralvarep please try this #83. I tested it on a clean VM and it correctly works for me.

**Comment by ralvarep** [comment]
Hi @amarsico,

I have tried the netip-fix-new branch and I continue having the same problem. Also, I have noticed a exception when I compile the Java Core #84 . Do you see it in your VM too? I am using 1.4.1-SNAPSHOT version of ONOS.

Thanks!

**Comment by amarsico** [comment]
Hi @ralvarep,
I tried the ONOS shim on a clean VM and correctly compiles and works. Please follow the README (ONOS uses different command to load applications in Karaf) and use the ONOS version 1.4.0 (not 1.4.1-SNAPSHOT), because this is the version of ONOS API used by the shim. I did not make changes to the shim after its first stable version. The only changes where in the NetIP library, which is a dependency.

Remember to recompile the CORE and, before compiling, sometimes deleting the maven local repository folder of NetIDE helps. In my case (rm -r ~/.m2/repository/eu/netide).

If you start ONOS in your local machine using `ok clean` , remember to setup ONOS karaf with `onos-setup-karaf clean` every time you change and compile a new ONOS version.

Using #83 solves a bug that I found in the CORE when it is running (like missing logging libraries or Google Guava).

Hope this helps.

**Comment by ralvarep** [comment]
Hi @amarsico,

Finally I fixed the problem. I think that I had a bit of mess in maven repository. I was using some instructions with _sudo_ and another without _sudo_, and as a result I had two local repositories. I edited _$M2_HOME/conf/settings.xml_ to set one local repository and now is ok. Thank you so much.

Now I can launch the ONOS shim but I have two issues:
- When I install the core feautre in Karaf I have the following output that I didn't see before:

```
        __ __                  ____      
       / //_/____ __________ _/ __/      
      / ,<  / __ `/ ___/ __ `/ /_        
     / /| |/ /_/ / /  / /_/ / __/        
    /_/ |_|\__,_/_/   \__,_/_/         

  Apache Karaf (3.0.5)

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown Karaf.

karaf@root()> feature:repo-add mvn:eu.netide.core/core.features/1.1.0-SNAPSHOT/xml/features
Adding feature url mvn:eu.netide.core/core.features/1.1.0-SNAPSHOT/xml/features
karaf@root()> feature:install core
java.lang.ArrayIndexOutOfBoundsException: 42752
    at aQute.bnd.osgi.Clazz.classConstRef(Clazz.java:1862)
    at aQute.bnd.osgi.Clazz.crawl(Clazz.java:1174)
    at aQute.bnd.osgi.Clazz.doCode(Clazz.java:1134)
    at aQute.bnd.osgi.Clazz.doAttribute(Clazz.java:945)
    at aQute.bnd.osgi.Clazz.doAttributes(Clazz.java:910)
    at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:741)
    at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:494)
    at aQute.bnd.osgi.Clazz.parseClassFileWithCollector(Clazz.java:483)
    at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:473)
    at aQute.bnd.osgi.Analyzer.analyzeJar(Analyzer.java:2177)
    at aQute.bnd.osgi.Analyzer.analyzeBundleClasspath(Analyzer.java:2083)
    at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:138)
    at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:616)
    at org.ops4j.pax.swissbox.bnd.BndUtils.createBundle(BndUtils.java:161)
    at org.ops4j.pax.url.wrap.internal.Connection.getInputStream(Connection.java:83)
    at java.net.URL.openStream(URL.java:1045)
    at org.apache.karaf.features.internal.BundleManager.getInputStreamForBundle(BundleManager.java:230)
    at org.apache.karaf.features.internal.BundleManager.doInstallBundleIfNeeded(BundleManager.java:96)
    at org.apache.karaf.features.internal.BundleManager.installBundleIfNeeded(BundleManager.java:90)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.doInstallFeature(FeaturesServiceImpl.java:581)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatureDependency(FeaturesServiceImpl.java:650)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.doInstallFeature(FeaturesServiceImpl.java:572)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatureDependency(FeaturesServiceImpl.java:650)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.doInstallFeature(FeaturesServiceImpl.java:572)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:436)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:417)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:392)
    at Proxyf9b4fdfb_4db3_4efe_81ee_04e66389967f.installFeature(Unknown Source)
    at org.apache.karaf.features.command.InstallFeatureCommand.doExecute(InstallFeatureCommand.java:72)
    at org.apache.karaf.features.command.FeaturesCommandSupport.doExecute(FeaturesCommandSupport.java:38)
    at org.apache.karaf.shell.console.AbstractAction.execute(AbstractAction.java:33)
    at org.apache.karaf.shell.console.OsgiCommandSupport.execute(OsgiCommandSupport.java:39)
    at org.apache.karaf.shell.commands.basic.AbstractCommand.execute(AbstractCommand.java:33)
    at Proxy1cae8ee2_48a9_4825_97ee_21b7e4b9aaa6.execute(Unknown Source)
    at Proxy1cae8ee2_48a9_4825_97ee_21b7e4b9aaa6.execute(Unknown Source)
    at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:78)
    at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:480)
    at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:406)
    at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
    at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:182)
    at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:119)
    at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:94)
    at org.apache.karaf.shell.console.impl.jline.ConsoleImpl.run(ConsoleImpl.java:210)
    at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1$1.run(LocalConsoleManager.java:109)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.apache.karaf.jaas.modules.JaasHelper.doAs(JaasHelper.java:57)
    at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1.run(LocalConsoleManager.java:102)
java.lang.ArrayIndexOutOfBoundsException: 42752
    at aQute.bnd.osgi.Clazz.classConstRef(Clazz.java:1862)
    at aQute.bnd.osgi.Clazz.crawl(Clazz.java:1174)
    at aQute.bnd.osgi.Clazz.doCode(Clazz.java:1134)
    at aQute.bnd.osgi.Clazz.doAttribute(Clazz.java:945)
    at aQute.bnd.osgi.Clazz.doAttributes(Clazz.java:910)
    at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:741)
    at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:494)
    at aQute.bnd.osgi.Clazz.parseClassFileWithCollector(Clazz.java:483)
    at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:473)
    at aQute.bnd.osgi.Analyzer.analyzeJar(Analyzer.java:2177)
    at aQute.bnd.osgi.Analyzer.analyzeBundleClasspath(Analyzer.java:2083)
    at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:138)
    at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:616)
    at org.ops4j.pax.swissbox.bnd.BndUtils.createBundle(BndUtils.java:161)
    at org.ops4j.pax.url.wrap.internal.Connection.getInputStream(Connection.java:83)
    at java.net.URL.openStream(URL.java:1045)
    at org.apache.karaf.features.internal.BundleManager.getInputStreamForBundle(BundleManager.java:230)
    at org.apache.karaf.features.internal.BundleManager.isBundleInstalled(BundleManager.java:163)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.doInstallFeature(FeaturesServiceImpl.java:603)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatureDependency(FeaturesServiceImpl.java:650)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.doInstallFeature(FeaturesServiceImpl.java:572)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatureDependency(FeaturesServiceImpl.java:650)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.doInstallFeature(FeaturesServiceImpl.java:572)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:436)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:417)
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:392)
    at Proxyf9b4fdfb_4db3_4efe_81ee_04e66389967f.installFeature(Unknown Source)
    at org.apache.karaf.features.command.InstallFeatureCommand.doExecute(InstallFeatureCommand.java:72)
    at org.apache.karaf.features.command.FeaturesCommandSupport.doExecute(FeaturesCommandSupport.java:38)
    at org.apache.karaf.shell.console.AbstractAction.execute(AbstractAction.java:33)
    at org.apache.karaf.shell.console.OsgiCommandSupport.execute(OsgiCommandSupport.java:39)
    at org.apache.karaf.shell.commands.basic.AbstractCommand.execute(AbstractCommand.java:33)
    at Proxy1cae8ee2_48a9_4825_97ee_21b7e4b9aaa6.execute(Unknown Source)
    at Proxy1cae8ee2_48a9_4825_97ee_21b7e4b9aaa6.execute(Unknown Source)
    at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:78)
    at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:480)
    at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:406)
    at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
    at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:182)
    at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:119)
    at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:94)
    at org.apache.karaf.shell.console.impl.jline.ConsoleImpl.run(ConsoleImpl.java:210)
    at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1$1.run(LocalConsoleManager.java:109)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.apache.karaf.jaas.modules.JaasHelper.doAs(JaasHelper.java:57)
    at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1.run(LocalConsoleManager.java:102)
karaf@root()> 
```
- Testing the ONOS shim with Ryu backend (sw+fw) and mininet, both with OF1.0 (with OF1.3 it works correctly), the results of pingall are not ok. Alice, Bob and WWW cannot ping charlie. Look:

```
---- Mininet: netide-topo:of10(protocol):(port) ----
*** Creating network
*** Adding controller
*** Adding hosts:
alice bob charlie www 
*** Adding switches:
s11 s21 s22 s23 
*** Adding links:
(s11, charlie) (s11, s21) (s22, alice) (s22, bob) (s22, s21) (s23, s21) (s23, www) 
*** Configuring hosts
alice bob charlie www 
*** Starting controller
c0 
*** Starting 4 switches
s11 s21 s22 s23 ...
*** Starting CLI:
mininet> 
mininet> 
mininet> 
mininet> pingall
*** Ping: testing ping reachability
alice -> bob X www 
bob -> alice X www 
charlie -> X X X 
www -> alice bob X 
*** Results: 50% dropped (6/12 received)
mininet> 
mininet> 
mininet> pingall
*** Ping: testing ping reachability
alice -> bob X www 
bob -> alice X www 
charlie -> X X X 
www -> alice bob X 
*** Results: 50% dropped (6/12 received)
mininet> 
mininet> 
mininet> pingall
*** Ping: testing ping reachability
alice -> bob X www 
bob -> alice X www 
charlie -> X X X 
www -> alice bob X 
*** Results: 50% dropped (6/12 received)
```

But if right after I try individual pings I have the next output:

```
mininet> charlie ping alice
PING 10.0.0.1 (10.0.0.1) 56(84) bytes of data.
^C
--- 10.0.0.1 ping statistics ---
37 packets transmitted, 0 received, 100% packet loss, time 36109ms

mininet> 
mininet> alice ping charlie
PING 10.0.0.3 (10.0.0.3) 56(84) bytes of data.
64 bytes from 10.0.0.3: icmp_seq=2 ttl=64 time=104 ms
64 bytes from 10.0.0.3: icmp_seq=3 ttl=64 time=16.5 ms
64 bytes from 10.0.0.3: icmp_seq=4 ttl=64 time=0.133 ms
64 bytes from 10.0.0.3: icmp_seq=5 ttl=64 time=0.035 ms
^C
--- 10.0.0.3 ping statistics ---
5 packets transmitted, 4 received, 20% packet loss, time 4017ms
rtt min/avg/max/mdev = 0.035/30.409/104.905/43.533 ms
mininet> 
mininet> bob ping charlie
PING 10.0.0.3 (10.0.0.3) 56(84) bytes of data.
64 bytes from 10.0.0.3: icmp_seq=2 ttl=64 time=9.29 ms
64 bytes from 10.0.0.3: icmp_seq=3 ttl=64 time=0.130 ms
64 bytes from 10.0.0.3: icmp_seq=4 ttl=64 time=0.052 ms
64 bytes from 10.0.0.3: icmp_seq=5 ttl=64 time=0.039 ms
^C
--- 10.0.0.3 ping statistics ---
5 packets transmitted, 4 received, 20% packet loss, time 4023ms
rtt min/avg/max/mdev = 0.039/2.378/9.294/3.993 ms
```

Pings work, but the first ping (with ICMP sequence 1) is lost. 

Do you have the same behaviour? Thanks!

**Comment by amarsico** [comment]
Hi @ralvarep,
For the first issue, please refer to #82 

About the second issue: I didn't have such issue when I tested the code with the Advanced Python Core. Check that the forwarding app of ONOS is deactivated:

`onos> app deactivate org.onosproject.fwd`

and remember to allow extraneous rules:

`onos> onos:cfg set org.onosproject.net.flow.impl.FlowRuleManager allowExtraneousRules true`

Best

**Comment by ralvarep** [comment]
Hi @amarsico ,

Regarding the second issue, I have tested it again from scratch and I continue having the same problem. I am testing Java Core + ONOS Shim + Ryu Backends (sw+fw) with OF 1.0. The behaviour is the same that I told you in the last message, the results of pingall are not ok because the first ping packet that goes through the switch that works as firewall is dropped:

```
mininet> pingall
*** Ping: testing ping reachability
alice -> bob X www 
bob -> alice X www 
charlie -> X X X 
www -> alice bob X 
*** Results: 50% dropped (6/12 received)

mininet> alice ping charlie
PING 10.0.0.3 (10.0.0.3) 56(84) bytes of data.
64 bytes from 10.0.0.3: icmp_seq=2 ttl=64 time=104 ms
64 bytes from 10.0.0.3: icmp_seq=3 ttl=64 time=16.5 ms

mininet> bob ping charlie
PING 10.0.0.3 (10.0.0.3) 56(84) bytes of data.
64 bytes from 10.0.0.3: icmp_seq=2 ttl=64 time=9.29 ms
64 bytes from 10.0.0.3: icmp_seq=3 ttl=64 time=0.130 ms
```

I have the forwarding application of ONOS disabled and I execute _onos:cfg_ to allow extraneous rules.

If I try with another shim (ODL or Ryu) it works correctly, but trying with Advanced Python Core I have the same behaviour:

![captura de pantalla de 2016-04-05 17 48 40](https://cloud.githubusercontent.com/assets/3491919/14288403/d010cd7c-fb56-11e5-91f8-285605e11898.png)

**Comment by ElisaRojas** [comment]
Hi @amarsico , I think we might be missing something. Could you give us all the details of your installation? Even maybe the cell information (although this should not be a problem at all). We are following all the steps in the README and the ones you told us. And @ralvarep has installed everything in a clean machine to have a "second chance" and still the same result... we are using the last code from the master branch of all the components, and you?

In the meantime, @sergiotamu is also trying to install the ONOS shim... to have a third opinion.

**Comment by amarsico** [comment]
Hi @ElisaRojas and @ralvarep,
Tomorrow I will try again with the Java Core. I think that there is an application that intercepts packet ins before the shim. Probably is the proxyarp. I will try and let you know. Also I will update the readme with a new command to setup the right ONOS applications at startup.

**Comment by amarsico** [comment]
Hi @ralvarep,
could you please provide me the Mininet topology that you are using and the composition file?
I'm trying to use `DpidPartitionABCW.xml` because I'm using Roberto's topology and Ryu applications (simple_switch.py and simple_firewall.py) but I'm always receiving the message: 

`Composition empty for packet, ignoring packet`

Thanks

**Comment by ralvarep** [comment]
Hi @amarsico, we think that you are using the same Mininet topology as us. We are using [this topology (Engine/ryu-backend/tests/netide-topo.py)](https://github.com/fp7-netide/Engine/blob/master/ryu-backend/tests/netide-topo.py) with [this composition file (Engine/core/specification/DpidPartitionABCW.xml)](https://github.com/fp7-netide/Engine/blob/master/core/specification/DpidPartitionABCW.xml) in the Java core.

**Comment by amarsico** [comment]
Hi @ralvarep,
I found the issue. It was not of the ONOS shim but the `simple_firewall.py`. The buffer of the `packet out` were not handled correctly and OpenvSwitch did not apply the `packet out` command.
On the other side, the `simple_firewall13.py` does not have this issue, probably I fixed it in the past. So if you had tried it, the ONOS shim would have worked correctly.

Probably the other shims have other operations when a packet out arrives, ONOS shim simply forwards what the backend/core sends.

I push a fix to that on the master. Please try it.

**Comment by sergiotamu** [comment]
Hello @amarsico, @ralvarep,

I have just tested with the latest version of the Engine repo and I obtain the expected outcomes (when I execute the pingall command you receive 11/12). The scenario I have tested is: Ryu backend (with sw and fw app of 1.0.) + AdvanceProxyCore + onos shim + Roberto's topology for of 1.0.

Good job =)
Best Regards,

**Comment by ralvarep** [comment]
Hi @amarsico, I have checked it too and now it works correctly. I have tested Java Core with OF10 and OF13. Thank you very much! I close this issue.

**Comment by sergiotamu** [comment]
Hello @amarsico and @ralvarep,

I reopen this issue because I am hvaing some troubles when I execute the onos shim with OF1.3. I have tested the following scenario: Ryu backend (sw app and fw app for =F1.3.) + Python Core + onos shim + Roberto's Topology for OF1.3.

In the Onos shim I obtain this error:
2016-04-07 18:52:07,144 | ERROR | ew I/O worker #2 | OFChannelHandler                 | 170 - org.onosproject.onos-of-ctl - 1.4.0 | OFBadRequestErrorMsgVer13(xid=5, code=BAD_TYPE, data=OFGroupStatsRequestVer13(xid=5, flags=[], group=all)) from switch org.onosproject.driver.handshaker.NiciraSwitchHandshaker [/127.0.0.1:42704 DPID[00:00:00:00:00:00:00:03]] in state ACTIVE
2016-04-07 18:52:07,144 | ERROR | ew I/O worker #4 | OFChannelHandler                 | 170 - org.onosproject.onos-of-ctl - 1.4.0 | OFBadRequestErrorMsgVer13(xid=7, code=BAD_TYPE, data=OFGroupStatsRequestVer13(xid=7, flags=[], group=all)) from switch org.onosproject.driver.handshaker.NiciraSwitchHandshaker [/127.0.0.1:42706 DPID[00:00:00:00:00:00:00:01]] in state ACTIVE
2016-04-07 18:52:07,145 | ERROR | ew I/O worker #5 | OFChannelHandler                 | 170 - org.onosproject.onos-of-ctl - 1.4.0 | OFBadRequestErrorMsgVer13(xid=1, code=BAD_TYPE, data=OFGroupStatsRequestVer13(xid=1, flags=[], group=all)) from switch org.onosproject.driver.handshaker.NiciraSwitchHandshaker [/127.0.0.1:42707 DPID[00:00:00:00:00:00:00:02]] in state ACTIVE
2016-04-07 18:52:07,145 | ERROR | ew I/O worker #3 | OFChannelHandler                 | 170 - org.onosproject.onos-of-ctl - 1.4.0 | OFBadRequestErrorMsgVer13(xid=3, code=BAD_TYPE, data=OFGroupStatsRequestVer13(xid=3, flags=[], group=all)) from switch org.onosproject.driver.handshaker.NiciraSwitchHandshaker [/127.0.0.1:42705 DPID[00:00:00:00:00:00:00:0a]] in state ACTIVE
2016-04-07 18:52:07,146 | ERROR | ew I/O worker #3 | OFChannelHandler                 | 170 - org.onosproject.onos-of-ctl - 1.4.0 | OFBadRequestErrorMsgVer13(xid=4, code=BAD_TYPE, data=OFGroupDescStatsRequestVer13(xid=4, flags=[])) from switch org.onosproject.driver.handshaker.NiciraSwitchHandshaker [/127.0.0.1:42705 DPID[00:00:00:00:00:00:00:0a]] in state ACTIVE
2016-04-07 18:52:07,146 | ERROR | ew I/O worker #4 | OFChannelHandler                 | 170 - org.onosproject.onos-of-ctl - 1.4.0 | OFBadRequestErrorMsgVer13(xid=8, code=BAD_TYPE, data=OFGroupDescStatsRequestVer13(xid=8, flags=[])) from switch org.onosproject.driver.handshaker.NiciraSwitchHandshaker [/127.0.0.1:42706 DPID[00:00:00:00:00:00:00:01]] in state ACTIVE
2016-04-07 18:52:07,149 | ERROR | ew I/O worker #2 | OFChannelHandler                 | 170 - org.onosproject.onos-of-ctl - 1.4.0 | OFBadRequestErrorMsgVer13(xid=6, code=BAD_TYPE, data=OFGroupDescStatsRequestVer13(xid=6, flags=[])) from switch org.onosproject.driver.handshaker.NiciraSwitchHandshaker [/127.0.0.1:42704 DPID[00:00:00:00:00:00:00:03]] in state ACTIVE
2016-04-07 18:52:07,149 | ERROR | ew I/O worker #5 | OFChannelHandler                 | 170 - org.onosproject.onos-of-ctl - 1.4.0 | OFBadRequestErrorMsgVer13(xid=2, code=BAD_TYPE, data=OFGroupDescStatsRequestVer13(xid=2, flags=[])) from switch org.onosproject.driver.handshaker.NiciraSwitchHandshaker [/127.0.0.1:42707 DPID[00:00:00:00:00:00:00:02]] in state ACTIVE

And the behaviour when I pingall in mininet is not the expected one:
mininet> pingall
**\* Ping: testing ping reachability
alice -> bob X www 
bob -> alice X www 
charlie -> X X X 
www -> alice bob X 
**\* Results: 50% dropped (6/12 received)

The hosts CANNOT ping charlie:
mininet> alice ping charlie
PING 10.0.0.3 (10.0.0.3) 56(84) bytes of data.
^C
--- 10.0.0.3 ping statistics ---
46 packets transmitted, 0 received, 100% packet loss, time 45001ms

Why do you think this is happening??
Thanks a lot =)

**Comment by amarsico** [comment]
Hi @sergiotamu,
the error is not related to ONOS shim but it is caused by OpenvSwitch. Mininet installs an OVS version that does not support OF 1.3 Group stats, but this is not an issue. I'm using OVS 2.4.0, this should be the only difference between us. I installed it to overcome this annoying log.

I've just tried with the OF 1.3 Ryu applications and it correctly works. However, I've just pushed a small modification to `firewall_13.py`. ONOS shim changes the flow mod priorities to a `value > 5` because otherwise it will create issues with other ONOS core components. Now the firewall installs directly flow mods with `priority = 6`. I will check if this method creates errors, but the `firewall_13.py` worked correctly without modifications for me.
